services:
  db:
    image: postgres:16-alpine
    container_name: avito_internship_db
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: avito_internship_app
    container_name: avito_internship_app
    depends_on:
      - db
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_PORT: "${APP_PORT:-8080}"
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: "${DB_PORT:-5432}"
      DB_NAME: ${DB_NAME:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:${APP_PORT:-8080}/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: